# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'myUi.명령어'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHeaderView, QLabel,
    QMainWindow, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(535, 718)
        icon = QIcon(QIcon.fromTheme(u"x-office-calendar"))
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.bttnLoad01 = QPushButton(self.centralwidget)
        self.bttnLoad01.setObjectName(u"bttnLoad01")
        self.bttnLoad01.setGeometry(QRect(460, 50, 61, 31))
        self.bttnLoad02 = QPushButton(self.centralwidget)
        self.bttnLoad02.setObjectName(u"bttnLoad02")
        self.bttnLoad02.setGeometry(QRect(460, 90, 61, 31))
        self.bttnLoad03 = QPushButton(self.centralwidget)
        self.bttnLoad03.setObjectName(u"bttnLoad03")
        self.bttnLoad03.setGeometry(QRect(460, 130, 61, 31))
        self.bttnStartWork = QPushButton(self.centralwidget)
        self.bttnStartWork.setObjectName(u"bttnStartWork")
        self.bttnStartWork.setGeometry(QRect(280, 620, 61, 31))
        self.bttnExit = QPushButton(self.centralwidget)
        self.bttnExit.setObjectName(u"bttnExit")
        self.bttnExit.setGeometry(QRect(430, 620, 81, 31))
        self.plainTextEdit01 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit01.setObjectName(u"plainTextEdit01")
        self.plainTextEdit01.setEnabled(False)
        self.plainTextEdit01.setGeometry(QRect(70, 50, 381, 31))
        self.plainTextEdit01.setFrameShape(QFrame.Box)
        self.plainTextEdit02 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit02.setObjectName(u"plainTextEdit02")
        self.plainTextEdit02.setEnabled(False)
        self.plainTextEdit02.setGeometry(QRect(70, 90, 381, 31))
        self.plainTextEdit02.setFrameShape(QFrame.Box)
        self.plainTextEdit03 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit03.setObjectName(u"plainTextEdit03")
        self.plainTextEdit03.setEnabled(False)
        self.plainTextEdit03.setGeometry(QRect(70, 130, 381, 31))
        self.plainTextEdit03.setFrameShape(QFrame.Box)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 48, 31))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 80, 48, 31))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 120, 48, 31))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 240, 48, 31))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(70, 250, 461, 311))
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setDocumentMode(True)
        self.tab01 = QWidget()
        self.tab01.setObjectName(u"tab01")
        self.table01 = QTableWidget(self.tab01)
        if (self.table01.columnCount() < 4):
            self.table01.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.table01.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.table01.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.table01.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.table01.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        if (self.table01.rowCount() < 1):
            self.table01.setRowCount(1)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.table01.setItem(0, 0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.table01.setItem(0, 1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.table01.setItem(0, 2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.table01.setItem(0, 3, __qtablewidgetitem7)
        self.table01.setObjectName(u"table01")
        self.table01.setGeometry(QRect(0, 30, 451, 251))
        self.table01.setMinimumSize(QSize(451, 200))
        self.table01.setMaximumSize(QSize(451, 16777215))
        self.table01.setTabletTracking(False)
        self.table01.setDragEnabled(True)
        self.table01.setAlternatingRowColors(True)
        self.table01.setShowGrid(True)
        self.table01.setGridStyle(Qt.SolidLine)
        self.table01.setSortingEnabled(False)
        self.bttnCreateRow01 = QPushButton(self.tab01)
        self.bttnCreateRow01.setObjectName(u"bttnCreateRow01")
        self.bttnCreateRow01.setGeometry(QRect(0, 0, 61, 31))
        self.tabWidget.addTab(self.tab01, "")
        self.tab02 = QWidget()
        self.tab02.setObjectName(u"tab02")
        self.table02 = QTableWidget(self.tab02)
        if (self.table02.columnCount() < 1):
            self.table02.setColumnCount(1)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.table02.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        if (self.table02.rowCount() < 1):
            self.table02.setRowCount(1)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.table02.setItem(0, 0, __qtablewidgetitem9)
        self.table02.setObjectName(u"table02")
        self.table02.setGeometry(QRect(0, 30, 181, 251))
        self.table02.setFrameShape(QFrame.StyledPanel)
        self.table02.setAlternatingRowColors(False)
        self.table02.setSortingEnabled(True)
        self.bttnCreateRow02 = QPushButton(self.tab02)
        self.bttnCreateRow02.setObjectName(u"bttnCreateRow02")
        self.bttnCreateRow02.setGeometry(QRect(0, 0, 61, 31))
        self.tabWidget.addTab(self.tab02, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.table03 = QTableWidget(self.tab)
        if (self.table03.columnCount() < 1):
            self.table03.setColumnCount(1)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.table03.setHorizontalHeaderItem(0, __qtablewidgetitem10)
        if (self.table03.rowCount() < 4):
            self.table03.setRowCount(4)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.table03.setVerticalHeaderItem(0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.table03.setVerticalHeaderItem(1, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.table03.setVerticalHeaderItem(2, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.table03.setVerticalHeaderItem(3, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.table03.setItem(0, 0, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.table03.setItem(1, 0, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.table03.setItem(2, 0, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.table03.setItem(3, 0, __qtablewidgetitem18)
        self.table03.setObjectName(u"table03")
        self.table03.setGeometry(QRect(0, 0, 381, 251))
        self.table03.setFrameShape(QFrame.StyledPanel)
        self.table03.setAlternatingRowColors(False)
        self.table03.setSortingEnabled(True)
        self.table03.setRowCount(4)
        self.tabWidget.addTab(self.tab, "")
        self.bttnSaveConfig = QPushButton(self.centralwidget)
        self.bttnSaveConfig.setObjectName(u"bttnSaveConfig")
        self.bttnSaveConfig.setGeometry(QRect(10, 620, 71, 31))
        self.bttnLoadConfig = QPushButton(self.centralwidget)
        self.bttnLoadConfig.setObjectName(u"bttnLoadConfig")
        self.bttnLoadConfig.setGeometry(QRect(80, 620, 71, 31))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 160, 48, 31))
        self.plainTextEdit04 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit04.setObjectName(u"plainTextEdit04")
        self.plainTextEdit04.setEnabled(True)
        self.plainTextEdit04.setGeometry(QRect(70, 170, 381, 31))
        self.plainTextEdit04.setFrameShape(QFrame.Box)
        self.plainTextEdit05 = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit05.setObjectName(u"plainTextEdit05")
        self.plainTextEdit05.setEnabled(True)
        self.plainTextEdit05.setGeometry(QRect(70, 210, 381, 31))
        self.plainTextEdit05.setFrameShape(QFrame.Box)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 200, 48, 31))
        self.bttnStartTest = QPushButton(self.centralwidget)
        self.bttnStartTest.setObjectName(u"bttnStartTest")
        self.bttnStartTest.setGeometry(QRect(220, 620, 61, 31))
        self.bttnShowLog = QPushButton(self.centralwidget)
        self.bttnShowLog.setObjectName(u"bttnShowLog")
        self.bttnShowLog.setGeometry(QRect(160, 620, 61, 31))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 590, 131, 21))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(160, 590, 51, 21))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(370, 10, 161, 21))
        self.bttnForceStop = QPushButton(self.centralwidget)
        self.bttnForceStop.setObjectName(u"bttnForceStop")
        self.bttnForceStop.setGeometry(QRect(340, 620, 61, 31))
        self.bttnShowUsage = QPushButton(self.centralwidget)
        self.bttnShowUsage.setObjectName(u"bttnShowUsage")
        self.bttnShowUsage.setGeometry(QRect(10, 10, 51, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        self.bttnLoad01.raise_()
        self.bttnLoad02.raise_()
        self.bttnStartWork.raise_()
        self.bttnExit.raise_()
        self.plainTextEdit01.raise_()
        self.plainTextEdit02.raise_()
        self.plainTextEdit03.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.bttnLoad03.raise_()
        self.label_4.raise_()
        self.tabWidget.raise_()
        self.bttnSaveConfig.raise_()
        self.bttnLoadConfig.raise_()
        self.label_5.raise_()
        self.plainTextEdit04.raise_()
        self.plainTextEdit05.raise_()
        self.label_6.raise_()
        self.bttnStartTest.raise_()
        self.bttnShowLog.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.bttnForceStop.raise_()
        self.bttnShowUsage.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 535, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\uc5d1\uc140\ubd84\ub9ac \ud504\ub85c\uadf8\ub7a8", None))
        self.bttnLoad01.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c\uc120\ud0dd", None))
        self.bttnLoad02.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c\uc120\ud0dd", None))
        self.bttnLoad03.setText(QCoreApplication.translate("MainWindow", u"\ud3f4\ub354\uc120\ud0dd", None))
        self.bttnStartWork.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\uc791", None))
        self.bttnExit.setText(QCoreApplication.translate("MainWindow", u"\ud504\ub85c\uadf8\ub7a8\uc885\ub8cc", None))
        self.plainTextEdit01.setPlainText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8\ud30c\uc77c\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694", None))
        self.plainTextEdit02.setPlainText(QCoreApplication.translate("MainWindow", u"\uc591\uc2dd\ud30c\uc77c\uc744 \uc120\ud0dd\ud574\uc8fc\uc138\uc694", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uc6d0\ubcf8\ud30c\uc77c", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uc591\uc2dd\ud30c\uc77c", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\uacbd\ub85c", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\uc791\uc5c5\uc815\uc758", None))
        ___qtablewidgetitem = self.table01.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\ud2b8 \uba85\uce6d", None));
        ___qtablewidgetitem1 = self.table01.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"\ud544\ud130 \uc704\uce58", None));
        ___qtablewidgetitem2 = self.table01.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"\ubcf5\uc0ac \ubc94\uc704", None));
        ___qtablewidgetitem3 = self.table01.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"\ubd99\uc5ec\ub123\uae30 \uc704\uce58", None));

        __sortingEnabled = self.table01.isSortingEnabled()
        self.table01.setSortingEnabled(False)
        ___qtablewidgetitem4 = self.table01.item(0, 0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"\uc2dc\ud2b81", None));
        ___qtablewidgetitem5 = self.table01.item(0, 1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"2", None));
        ___qtablewidgetitem6 = self.table01.item(0, 2)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"A2:Z900", None));
        ___qtablewidgetitem7 = self.table01.item(0, 3)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"A2", None));
        self.table01.setSortingEnabled(__sortingEnabled)

        self.bttnCreateRow01.setText(QCoreApplication.translate("MainWindow", u"\ud589\ucd94\uac00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab01), QCoreApplication.translate("MainWindow", u"\ub300\uc0c1\uc2dc\ud2b8 \ubc0f \ubcf5\uc0ac\ubd99\uc5ec\ub123\uae30 \uc815\uc758", None))
        ___qtablewidgetitem8 = self.table02.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"\ubd84\ub9ac \ud0a4\uc6cc\ub4dc", None));

        __sortingEnabled1 = self.table02.isSortingEnabled()
        self.table02.setSortingEnabled(False)
        ___qtablewidgetitem9 = self.table02.item(0, 0)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"\ud0a4\uc6cc\ub4dc1", None));
        self.table02.setSortingEnabled(__sortingEnabled1)

        self.bttnCreateRow02.setText(QCoreApplication.translate("MainWindow", u"\ud589\ucd94\uac00", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab02), QCoreApplication.translate("MainWindow", u"\ubd84\ub9ac \ud0a4\uc6cc\ub4dc \uc815\uc758", None))
        ___qtablewidgetitem10 = self.table03.horizontalHeaderItem(0)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"\uc124\uc815\uac12", None));
        ___qtablewidgetitem11 = self.table03.verticalHeaderItem(0)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"\uc90c\ub808\ubca8(\uac1c\uc694\uc2dc\ud2b8)", None));
        ___qtablewidgetitem12 = self.table03.verticalHeaderItem(1)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"\uc90c\ub808\ubca8(\ub098\uba38\uc9c0\uc2dc\ud2b8)", None));
        ___qtablewidgetitem13 = self.table03.verticalHeaderItem(2)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"\ub208\uae08\uc120 \uc77c\uad04\uc81c\uac70", None));
        ___qtablewidgetitem14 = self.table03.verticalHeaderItem(3)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"\uacc4\uc0b0\uc2dd \ucc38\uc870\uacbd\ub85c\uc77c\uad04\uc81c\uac70", None));

        __sortingEnabled2 = self.table03.isSortingEnabled()
        self.table03.setSortingEnabled(False)
        ___qtablewidgetitem15 = self.table03.item(0, 0)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"100", None));
        ___qtablewidgetitem16 = self.table03.item(1, 0)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"100", None));
        ___qtablewidgetitem17 = self.table03.item(2, 0)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"N", None));
        ___qtablewidgetitem18 = self.table03.item(3, 0)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"N", None));
        self.table03.setSortingEnabled(__sortingEnabled2)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\uc635\uc158", None))
        self.bttnSaveConfig.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5", None))
        self.bttnLoadConfig.setText(QCoreApplication.translate("MainWindow", u"\ubd88\ub7ec\uc624\uae30", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\uba85\uce6d", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\ub0a0\uc9dc", None))
        self.bttnStartTest.setText(QCoreApplication.translate("MainWindow", u"\ud14c\uc2a4\ud2b8", None))
        self.bttnShowLog.setText(QCoreApplication.translate("MainWindow", u"\ub85c\uadf8\ubcf4\uae30", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\uc124\uc815 \uc800\uc7a5 \ubc0f \ubd88\ub7ec\uc624\uae30", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\uc791\uc5c5\uc218\ud589", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\uc81c\uc791: \uae40\uc9c0\uc5fd,  v2025.06.10", None))
        self.bttnForceStop.setText(QCoreApplication.translate("MainWindow", u"\uac15\uc81c\uc885\ub8cc", None))
        self.bttnShowUsage.setText(QCoreApplication.translate("MainWindow", u"\uc0ac\uc6a9\ubc95", None))
    # retranslateUi

